name       : freeplane
version    : 1.6.10
release    : 4
source     :
    - https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_src-1.6.10.tar.gz/download : 601be6ce66fdd4710d06e17aa6736cdcde5936b9183858d3d280a7a92f66a2a1
license    : GPL-2.0
component  : office
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    An application for Mind Mapping, plus Knowledge and Project Management
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
networking : yes
build      : |
    #sed -i "73 a options.addBooleanOption('Xdoclint:none', true)" build.gradle
    export GRADLE_USER_HOME=~/
    gradle --no-daemon build -x test
install    : |
    install -d $installdir/usr/share/freeplane
    cp -R BIN/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop
