name       : freeplane
version    : 1.7.10
release    : 8
source     :
    - https://liquidtelecom.dl.sourceforge.net/project/freeplane/freeplane%20stable/freeplane_src-1.7.10.tar.gz : 6d594eb0c5b237fdf5ae2b37743d3aae09a93d7a07552a5d598362e37ed30ec5
homepage   : https://www.freeplane.org
license    : GPL-2.0-or-later
component  : office
networking : yes
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    Freeplane is a free and open source software application that supports thinking, sharing information and getting things done at work, in school and at home. The software can be used for mind mapping and analyzing the information contained in mind maps. 
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
build      : |
    export GRADLE_USER_HOME=~/
    gradle --no-daemon build -x test
install    : |
    install -d $installdir/usr/share/freeplane
    cp -R BIN/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop

