name       : freeplane
version    : 1.5.17
release    : 2
source     :
    - http://netix.dl.sourceforge.net/project/freeplane/freeplane%20stable/freeplane_src-1.5.17.tar.gz : 44b539f65d2a1b17644704f1fdd57412b0b6cf49e85962a8a060a5aa0678d8e2
license    : GPL-2.0
component  : office
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    An application for Mind Mapping, plus Knowledge and Project Management
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
build      : |
    sed -i "73 a options.addBooleanOption('Xdoclint:none', true)" build.gradle
    gradle --no-daemon build -x test
install    : |-
    install -d $installdir/usr/share/freeplane
    cp -R BUILD/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop
