name       : freeplane
version    : 1.7.2
release    : 7
source     :
    - https://github.com/freeplane/freeplane/archive/release-1.7.2.tar.gz : 979330682f0f76387d9faecd131172d6013f14182a2267a800fc5cbb37b92ae6
license    : GPL-2.0
component  : office
networking : yes
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    An application for Mind Mapping, plus Knowledge and Project Management
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
build      : |
    export GRADLE_USER_HOME=~/
    gradle --no-daemon build -x test
install    : |
    install -d $installdir/usr/share/freeplane
    cp -R BIN/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop

