name       : freeplane
version    : 1.6.13
release    : 6
source     :
    - https://kent.dl.sourceforge.net/project/freeplane/freeplane%20stable/freeplane_src-1.6.13.tar.gz : 97b1f19297435ee69dc8cad0435268c42e80650e723ce96c7bcd0988a9b14b29
license    : GPL-2.0
component  : office
networking : yes
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    An application for Mind Mapping, plus Knowledge and Project Management
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
build      : |
    export GRADLE_USER_HOME=~/
    gradle --no-daemon build -x test
install    : |
    install -d $installdir/usr/share/freeplane
    cp -R BIN/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop

