name       : freeplane
version    : 1.6.4
release    : 3
source     :
    - https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_src-1.6.4.tar.gz/download : 32a7369af4fe320f36f1a58f76892f752e6173af8630f0a14b6bbbd0e87ded92
license    : GPL-2.0
component  : office
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    An application for Mind Mapping, plus Knowledge and Project Management
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
networking : yes
build      : |
    #sed -i "73 a options.addBooleanOption('Xdoclint:none', true)" build.gradle
    export GRADLE_USER_HOME=~/
    gradle --no-daemon build -x test
install    : |
    install -d $installdir/usr/share/freeplane
    cp -R BUILD/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop
