name       : freeplane
version    : 1.6.12
release    : 5
source     :
    - https://ncu.dl.sourceforge.net/project/freeplane/freeplane%20stable/freeplane_src-1.6.12.tar.gz : 91fe0a525e02a894b56720c8c33a1ba87749abec0e271830f775ec5427fbc338
license    : GPL-2.0
component  : office
summary    : An application for Mind Mapping, plus Knowledge and Project Management
description: |
    An application for Mind Mapping, plus Knowledge and Project Management
builddeps  :
    - gradle
rundeps    :
    - openjdk-8
networking : yes
build      : |
    #sed -i "73 a options.addBooleanOption('Xdoclint:none', true)" build.gradle
    export GRADLE_USER_HOME=~/
    gradle --no-daemon build -x test
install    : |
    install -d $installdir/usr/share/freeplane
    cp -R BIN/* $installdir/usr/share/freeplane/
    chmod -R 00644 $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh
    install -D -m00644 $pkgfiles/freeplane.desktop $installdir/usr/share/applications/freeplane.desktop
