name       : freeplane
version    : 1.8.5
release    : 10
source     :
    - https://github.com/freeplane/freeplane/archive/release-1.8.5.tar.gz : 68e9688ef3d689c13a219f8b6ccad90607ab08cdba9d1f84cd47f02a24def426
homepage   : https://www.freeplane.org
license    : GPL-2.0-or-later
component  : office
networking : yes
summary    : An application for mind mapping, plus knowledge and project management
description: |
    Freeplane is a free and open source software application that supports thinking, sharing information and getting things done at work, in school and at home. The software can be used for mind mapping and analyzing the information contained in mind maps.
builddeps  :
    - font-ubuntu-ttf   # Tests
    - fontconfig        # Tests
    - gradle
rundeps    :
    - fontconfig
    - openjdk-11
setup      : |
    rm -rf freeplane_mac
build      : |
    %patch -p1 < $pkgfiles/0001-fix-failing-gradle-build.patch
    export GRADLE_USER_HOME=$workdir/.gradle
    gradle --no-daemon build
install    : |
    install -dm00755 $installdir/usr/share/freeplane
    cp -a BIN/* $installdir/usr/share/freeplane
    chmod 00755 $installdir/usr/share/freeplane/freeplane.sh

    install -dm00755 $installdir/usr/share/icons/hicolor/{scalable,32x32}/apps
    ln -s /usr/share/freeplane/freeplane.svg $installdir/usr/share/icons/hicolor/scalable/apps/freeplane.svg
    ln -s /usr/share/freeplane/freeplane.png $installdir/usr/share/icons/hicolor/32x32/apps/freeplane.png

    install -Dm00644 $workdir/freeplane/src/editor/resources/linux/freeplane.desktop -t $installdir/usr/share/applications
    install -Dm00644 $workdir/debian-meta-data/freeplane.sharedmimeinfo $installdir/usr/share/mime/packages/freeplane.xml

    install -Dm00755 $pkgfiles/freeplane.sh $installdir/usr/bin/freeplane

    rm $installdir/usr/share/freeplane/{*.bat,*.dll}
